### ISSUE TITLE
Add option to add song books from local storage (or an URL)

### ISSUE THREAD

**Issue by ghost** [yukuku/androidbible#41]
I'm working on a spanish hymnal and wanted to try it in the app, to know how it'd look, and to see if there'd be any mistake, but I couldn't find a way to test it. There seems to be only an option to download song books, and not to add them from elsewhere (unlike with the bible versions). 

I think a single plus (+) sign at the top bar would be enough.

Thanks for all the great work!

**Comment by yukuku** [comment]
Yeah we haven't made the way for the song books to be self-managed, there are some compilers and proprietary format (java serialization format) that doesn't seem good for data interchange. It's very troublesome now because I made a bad decision. For now you can send the song book to help@bibleforandroid.com and we will add it as "private song book" (4.4 beta version) so you can test that first.

**Comment by ascuccaro** [comment]
Ok, thanks. I'll finish up some details and will send it later. Thanks again!
