### ISSUE TITLE
A Working Project Without Google Play Services

### ISSUE THREAD

**Issue by joielechong** [yukuku/androidbible#52]
I've successfully remove the google play service from alkitab project. I've found that the google play service library is used mainly for Tracking and Sync. If I remove the tracking, should we change to another library? And for sync, I found that it use gcm key as the id. How can we change the id without using gcm at all?

Thank you for your wonderful project.

Related issue: #39 #43

God bless you.

**Comment by joielechong** [comment]
I've forked the project and clean up the google play service. Still waiting confirmation about the Tracking and Sync features.
https://github.com/joielechong/androidbible

**Comment by yukuku** [comment]
Yes, the Google services are used for tracking and receiving push
notifications.

You can remove the tracking, but in order for the app to always have the
latest update of the bookmarks etc, the GCM is needed. Otherwise, the app
will only check for updates each time it is started. If you are okay with
this,you can remove GCM as well.
