### ISSUE TITLE
Feature request: Option to hide songs, devotional and reading plan buttons.

### ISSUE THREAD

**Issue by daniel-maurer** [yukuku/androidbible#53]
Add option to hide the songs, devotional and reading plan buttons.

**Comment by yukuku** [comment]
Hi Daniel,

I wonder why would you want this feature.

On Mar 15, 2017 19:26, "Daniel Maurer" <notifications@github.com> wrote:

Add option to hide the songs, devotional and reading plan buttons.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yukuku/androidbible/issues/53>, or mute the thread

**Comment by danielmaurer** [comment]
Hello,

I like much of the QuickBible because is easy to use but I do not use songs and devotional so this buttons are of no use for me and only occupy space. 

Best regards from Brazil,
Daniel Maurer

**Comment by yukuku** [comment]
Thanks for your explanation, however I will wait for more requests of the same feature before implementing this. I will close this issue for now.
